### ISSUE TITLE
Combining strings

### ISSUE THREAD

**Issue by isaacg1** [ibara/bf300#1]
Currently, four of the ASCII strings are:

```
	.ascii	"--p;"		# 4
	.ascii	"++p;"		# 4
	.ascii	"--*p;"		# 5
	.ascii	"++*p;"		# 5
```
If made the strings post-increment instead, we could could remove two of the strings:
```
	.ascii	"*p--;"		# 5
	.ascii	"*p++;"		# 5
```
The other two strings, `p--;` and `p++;`, are substrings of these strings, so they could be formed by starting the write 1 byte later. Does this work, or am I missing something?

Thanks for the post, it was fun to read!

**Comment by ibara** [comment]
Hello --

Sadly, `++*p` and `*p++` are not equivalent.
`++*p` means `++(*p)` whereas `*p++` means `*(p++)`.

**Comment by ibara** [comment]
Hello --

I was able to adapt your suggestion in order to save 6 bytes (+2, -8).
Thanks again.

**Comment by isaacg1** [comment]
I'm glad you were able to rework it into something correct - apologies that my initial version wasn't quite right.
